[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
one_kx_hook = "D6zrGzM98Mn4cKBtdQyqLRGD3JMMbYvCbTADMDzWFmnE"

[programs.devnet]
one_kx_hook = "HU8xgmKfWv16e77BX6DEDBCXv8wmdxhYH5TPTSEGu4E2"

[programs.mainnet]
one_kx_hook = "3JkDgnSWfgCmgmE4cvniHYWPzHnF7oJUwT7PwnK2TzvK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
