name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-program:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.78.0
          override: true
          components: rustfmt, clippy
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            programs/1kx_hook/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('programs/1kx_hook/Cargo.lock') }}
      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.0/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: Cache Solana
        uses: actions/cache@v3
        with:
          path: ~/.cache/solana
          key: ${{ runner.os }}-solana-${{ hashFiles('Anchor.toml') }}
      - name: Install Anchor
        run: cargo install --git https://github.com/coral-xyz/anchor anchor-cli --tag v0.29.0
      - name: Check Rust Formatting
        run: cargo fmt --all --manifest-path programs/1kx_hook/Cargo.toml -- --check
      - name: Run Clippy
        run: cargo clippy --manifest-path programs/1kx_hook/Cargo.toml -- -D warnings
      - name: Build Program
        run: anchor build
      - name: Run Rust Tests
        run: cargo test --manifest-path programs/1kx_hook/Cargo.toml

  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install Dependencies
        run: pnpm install
      - name: Check TypeScript Types
        run: npx tsc --noEmit
      - name: Run TypeScript Tests
        run: pnpm test:jest

  test-integration:
    runs-on: ubuntu-latest
    needs: [test-program, test-client]
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.78.0
          override: true
      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.0/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: Install Anchor
        run: cargo install --git https://github.com/coral-xyz/anchor anchor-cli --tag v0.29.0
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Start Local Validator
        run: |
          solana-test-validator --detach
          sleep 5
      - name: Run Integration Tests
        run: pnpm test:integration
        env:
          ANCHOR_PROVIDER_URL: http://localhost:8899
          ANCHOR_WALLET: ~/.config/solana/id.json

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.78.0
          override: true
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run Cargo Audit
        run: cargo audit
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Run npm audit
        run: pnpm audit
